### ISSUE TITLE
I'm curious that after downloading the file, the content is empty.

### ISSUE THREAD

**Issue by bitten-littlesuqirrel** [tonytan48/KD-DocRE#14]
![image](https://user-images.githubusercontent.com/40733610/188348787-00415c41-3636-48c3-ba1e-7666325b350f.png)
Sorry to disturb you again.
Because I changed a server, when I rerun step 2 for bert, **train_ distant.json.bert-base-cased.pt** file shows that it has been downloaded successfully, but when I opened it, I found that it was an empty file.
![image](https://user-images.githubusercontent.com/40733610/188349458-40b282d7-4139-4fd4-a599-ede397c19f49.png)

**Comment by tonytan48** [comment]
I suspect that the train_ distant.json.bert-base-cased.pt that you transferred across servers is not complete, since this file can be very large. 
You may try delete this file on your new server and then re-process the features of train_ distant.json, which is just running the same script after deletion of old file.

**Comment by bitten-littlesuqirrel** [comment]
Thank you very much for your suggestion. I have found the source of the problem.
