### ISSUE TITLE
Why not compare with SSAN-KD-Rb-l models that use knowledge distillation strategy?

### ISSUE THREAD

**Issue by WatsonWangZh** [tonytan48/KD-DocRE#2]

**Comment by tonytan48** [comment]
Hi Watson,
Thank you for your question. Actually, when I try to reproduce SSAN-KD, I found that it is hard to tune the threshold class. This is mainly because SSAN uses a global threshold and needed many tuning work. And the SSAN-Adapt part was not released so we did not run SSAN-NA and SSAN-KD by ourselves.
